# Given that a person has done psychedelics in the past month or year, are their odds of doing cocaine any less than other people?

In [9]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 
import scipy.stats as stats
sns.set_style("whitegrid")
df = pd.read_csv("drug_consumption_with_monthly_trip_rate.csv")
df["Alcohol"].value_counts()
df.head()

,Unnamed: 0,Unnamed: 0.1,ID,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,...,Meth,Mushrooms,Nicotine,Semer,VSA,Education Level,Tripped Shrooms?,Tripped LSD?,Tripped?,Tripped on how many?
0,0,0,1,35-44,Female,-0.05921,UK,Mixed-White/Asian,0.31287,-0.57545,...,CL0,CL0,CL2,CL0,CL0,Professional Certificate/ Diploma,0,0,0,0
1,1,1,2,25-34,Male,1.98437,UK,White,-0.67825,1.93886,...,CL3,CL0,CL4,CL0,CL0,Doctorate Degree,0,0,0,0
2,2,2,3,35-44,Male,-0.05921,UK,White,-0.46725,0.80523,...,CL0,CL1,CL0,CL0,CL0,Professional Certificate/ Diploma,0,0,0,0
3,3,3,4,18-24,Female,1.16365,UK,White,-0.14882,-0.80615,...,CL0,CL0,CL2,CL0,CL0,Masters Degree,0,0,0,0
4,4,4,5,35-44,Female,1.98437,UK,White,0.73545,-1.63340,...,CL0,CL2,CL2,CL0,CL0,Doctorate Degree,0,0,0,0

In [7]:
def hasDoneAlcInPastDay(x):
    if x == "CL0" or x == "CL1" or x == "CL2" or x == "CL3" or x == "CL4" or x == "CL5":
        return 0
    else:
        return 1 
df["AlcToday?"] = df["Alcohol"].apply(hasDoneAlcInPastDay)
df["AlcToday?"].value_counts()
#xvals = ["Has Not Done Meth in the Past Week", "Has Done Meth in the Past Week"]
#plt.bar(xvals, df["MethInThePastWeek?"].value_counts())
#plt.set_title("Have ")
#df.head()
#df[df[df["CokeInThePastWeek?"]==1]["Tripped?"] ==1]
counts = df[df["Tripped?"]==1]["AlcToday?"].value_counts()
print(counts[1] / (counts[0]+counts[1]))

print(counts)

0.27530364372469635
0    179
1     68
Name: AlcToday?, dtype: int64

In [8]:
counts = df[df["Tripped?"]==0]["AlcToday?"].value_counts()
print(counts[1] / (counts[0]+counts[1]))

print(counts)

0.2667887667887668
0    1201
1     437
Name: AlcToday?, dtype: int64

In [10]:
counts = df["MethInThePastWeek?"].value_counts()
counts[1] / (counts[0]+counts[1])

0.06419098143236074